# -*- coding: utf-8 -*-
"""HPI THIRD PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjwfOkIQgCZv58OmOkA9MvIw_IHQ2gkk
"""

from typing import List, TypedDict


class Task(TypedDict):
    """Represents a single task with a description and completion status."""
    description: str
    done: bool

def show_menu() -> None:
    """Print the main menu options for the task manager."""
    print("\n--- Task Manager ---")
    print("1) Add task")
    print("2) List tasks")
    print("3) Mark task as done")
    print("4) Delete task")
    print("5) Exit")

def list_tasks(tasks: List[Task]) -> None:
    """Display all tasks with their index and completion status."""
    if not tasks:
        print("There are no tasks yet.")
        return

    # Loop over all tasks and print each one with its number and status
    for index, task in enumerate(tasks, start=1):
        status: str = "✔" if task["done"] else "✘"
        print(f"{index}. [{status}] {task['description']}")

def add_task(tasks: List[Task]) -> None:
    """Ask the user for a task description and add it to the list."""
    description: str = input("New task description: ").strip()
    if not description:
        print("The task description cannot be empty.")
        return

    # Create a new task dictionary and append it to the list
    tasks.append({"description": description, "done": False})
    print("Task added successfully.")

def ask_for_task_index(tasks: List[Task], prompt: str) -> int | None:
    """
    Ask the user for a task number and convert it to a list index.
    Returns:
        The zero-based index of the chosen task, or None if invalid.
    """
    if not tasks:
        print("There are no tasks to choose from.")
        return None

    # Show tasks so the user can see the available numbers
    list_tasks(tasks)

    try:
        user_input: str = input(prompt)
        task_number: int = int(user_input)
    except ValueError:
        print("You must enter a valid number.")
        return None

    # Check that the chosen number is within the valid range
    if 1 <= task_number <= len(tasks):
        return task_number - 1

    print("That task number does not exist.")
    return None

def mark_task_as_done(tasks: List[Task]) -> None:
    """Mark a task as done based on the user's choice."""
    index: int | None = ask_for_task_index(tasks, "Task number to mark as done: ")
    if index is None:
        return

    # Update the chosen task's status to done
    tasks[index]["done"] = True
    print("Task marked as done.")

def delete_task(tasks: List[Task]) -> None:
    """Delete a task chosen by the user."""
    index: int | None = ask_for_task_index(tasks, "Task number to delete: ")
    if index is None:
        return

    # Remove the task from the list and show which task was deleted
    removed_task: Task = tasks.pop(index)
    print(f'Task "{removed_task["description"]}" has been deleted.')

def main() -> None:
    """Run the main loop of the task manager program."""
    tasks: List[Task] = []

    # Infinite loop: show menu and react to the user's choice
    while True:
        show_menu()
        choice: str = input("Choose an option: ").strip()

        if choice == "1":
            add_task(tasks)
        elif choice == "2":
            list_tasks(tasks)
        elif choice == "3":
            mark_task_as_done(tasks)
        elif choice == "4":
            delete_task(tasks)
        elif choice == "5":
            print("Goodbye!")
            break
        else:
            print("Invalid option. Please choose between 1 and 5.")

if __name__ == "__main__":
    main()